#!/usr/bin/env bash

yabai -m config layout bsp

yabai -m config window_placement second_child

yabai -m config top_padding 16
yabai -m config bottom_padding 16
yabai -m config left_padding 16
yabai -m config right_padding 16
yabai -m config window_gap 20

yabai -m config window_shadow off

yabai -m space 1 --label dev
yabai -m space 2 --label chat
yabai -m space 3 --label work
yabai -m space 4 --label web
yabai -m space 5 --label iOS
yabai -m space 6 --label notes
yabai -m space 7 --label 3d
yabai -m space 8 --label media
yabai -m space 9 --label scratch

if [[ -f /Users/steven0351/.config/yabai/yabai.user ]]; then
  source /Users/steven0351/.config/yabai/yabai.user
fi
